'''
Base models for the xDimension web project
'''

from django.db import models


class Map(models.Model):
    ''' Contains nodes connected into a graph.
    '''
    title = models.CharField(max_length=500, blank=True,
                             help_text='If blank, will be inferred from the tags')
    description = models.TextField(blank=True)
    picture = models.CharField(
        max_length=1000, blank=True,
        help_text='If blank auto-generated by this backend (not implemented yet)')
    map_data = models.TextField(help_text='json data from xDimension engine')

    # for sorting
    date_created = models.DateField(db_index=True)
    popularity = models.IntegerField(default=0, db_index=True)
    featured = models.IntegerField(default=0, db_index=True)

    # moved out of the original json
    thumbnail_img = models.ImageField(blank=True, upload_to='map_thumbnail')


class MapTopic(models.Model):
    ''' For searching. '''
    map = models.ForeignKey(Map)
    topic = models.CharField(max_length=500)
    relevance = models.IntegerField()

    class Meta:
        index_together = [
            ['topic', 'relevance']
        ]
